service: rtr-script-upload-and-processing

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.8
  region: us-east-1

functions:
  - ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 3003

plugins:
  - serverless-offline
  - serverless-python-requirements
